In [1]:
import numpy as np

In [8]:
a = np.random.randn(3, 2)

In [9]:
a

array([[ 0.55129488,  0.58971979],
       [-0.31379976, -0.20342884],
       [-0.56567388,  0.73574726]])

In [12]:
b = np.array([[2,20]])

In [13]:
b

array([[ 2, 20]])

In [14]:
a+b

array([[ 2.55129488, 20.58971979],
       [ 1.68620024, 19.79657116],
       [ 1.43432612, 20.73574726]])

In [2]:
import pandas as pd

In [3]:
path = "../../mlruns/results/"

In [4]:
df = pd.read_csv(path+"runs.csv")

In [6]:
df.columns

Index(['Start Time', 'Duration', 'Run ID', 'Name', 'Source Type',
       'Source Name', 'User', 'Status', 'features', 'model_class',
       'model_type', 'n_hidden_neurons', 'order_dyn', 'pred_mode',
       'pred_recursion', 'y_name', 'RMSE_test', 'RMSE_train', 'RMSE_val'],
      dtype='object')

In [7]:
df.sort_values(["y_name", "model_class", "model_type", "order_dyn", "n_hidden_neurons", "RMSE_val"], inplace=True)

In [10]:
df.columns

Index(['Start Time', 'Duration', 'Run ID', 'Name', 'Source Type',
       'Source Name', 'User', 'Status', 'features', 'model_class',
       'model_type', 'n_hidden_neurons', 'order_dyn', 'pred_mode',
       'pred_recursion', 'y_name', 'RMSE_test', 'RMSE_train', 'RMSE_val'],
      dtype='object')

In [16]:
cols = ['Duration', 'Run ID', 'features', 'model_class',
       'model_type', 'n_hidden_neurons', 'order_dyn',
       'pred_recursion', 'y_name', 'RMSE_test', 'RMSE_train', 'RMSE_val']

In [17]:
df[cols].to_excel(path+"runs.xlsx", index=False)

In [21]:
df[df['pred_recursion']==True][cols].to_excel(path+"runs_recursion.xlsx", index=False)

In [22]:
df[df['pred_recursion']==False][cols].to_excel(path+"runs_not_recursion.xlsx", index=False)

In [2]:
from sklearn.cluster import KMeans

In [3]:
def transform_column_name(df):
    df.columns = [col[0] for col in df.columns.str.split()]
    return df

In [4]:
data_path = "../../data/4_tanks/data/"

# dane bez zakłóceń
df_train = pd.read_csv(data_path+"result_ol_without_noise_uczące_v3.csv", sep=';', index_col=0)
df_val = pd.read_csv(data_path+"result_ol_without_noise_walidacyjne_v3.csv", sep=';', index_col=0)
df_test = pd.read_csv(data_path+"result_ol_without_noise_testowe_v3.csv", sep=';', index_col=0)
dataset_name = "bez zakłóceń"

df_train = transform_column_name(df_train)
df_val = transform_column_name(df_val)
df_test = transform_column_name(df_test)

NameError: name 'pd' is not defined

In [30]:
df_train

q_A      q_B  q_d1  q_d2  q_d3  q_d4          x1          x2  \
0     452.78   555.56   0.0   0.0   0.0   0.0   65.000000   66.000000   
1     452.78   555.56   0.0   0.0  -0.0   0.0   64.984326   65.937304   
2     452.78   555.56   0.0  -0.0   0.0  -0.0   64.971213   65.878615   
3     452.78   555.56   0.0   0.0  -0.0  -0.0   64.960438   65.823672   
4     452.78   555.56   0.0  -0.0   0.0  -0.0   64.951795   65.772231   
...      ...      ...   ...   ...   ...   ...         ...         ...   
2995  513.07  1111.00   0.0  -0.0   0.0  -0.0  197.357316  144.297403   
2996  513.07  1111.00  -0.0   0.0   0.0   0.0  197.410504  144.298737   
2997  513.07  1111.00  -0.0  -0.0  -0.0  -0.0  197.462623  144.300024   
2998  513.07  1111.00  -0.0   0.0  -0.0  -0.0  197.513694  144.301265   
2999  513.07  1111.00  -0.0   0.0   0.0   0.0  197.563738  144.302462   

              x3         x4  
0      65.000000  66.000000  
1      65.038198  65.992639  
2      65.074774  65.985573  
3      65.109799  65.978790  
4      65.143339  65.972278  
...          ...        ...  
2995  261.849369  84.499323  
2996  261.885388  84.499736  
2997  261.920646  84.500134  
2998  261.955159  84.500518  
2999  261.988941  84.500889  

[3000 rows x 10 columns]

In [5]:
import sys
import os

# Get the parent directory of the current notebook
module_path = os.path.abspath(os.path.join('..'))

# Add the model directory to the Python path
if module_path not in sys.path:
    sys.path.append(module_path)

In [6]:

from utils import *

In [67]:
n_centers = 3
X = df_train[['x1', 'x2']]
X = np.array(X)
y = df_train[['x4']]
sigma = np.ones((n_centers, 1))

In [38]:
kmeans = KMeans(n_clusters=n_centers)
kmeans.fit(X)

KMeans(n_clusters=3)

In [41]:
centers = kmeans.cluster_centers_

In [49]:
n_samples = X.shape[0]
activations = np.ones((n_samples, n_centers+1))

In [50]:
n_samples

3000

In [51]:
activations

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       ...,
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
activations[i][j+1]

1.0

In [61]:
gaussian_func(X[i], centers[j], sigma[j])

array([0.])

In [69]:
def _GD(X, y):
    print("y:")
    print(np.shape(y))
    pred = self.predict(X)
    print("pred:")
    print(np.shape(pred))
    print("weights:")
    print(np.shape(self.weights))
    n_samples = X.shape[0]
    grad_sum = np.zeros((self.n_centers, 1))
    for j in range(self.n_centers):
        for i in range(n_samples):
            grad_gauss = grad_gaussian_func(X[i], self.centers[j], self.sigma[j])
            print("grad_gauss:")
            print(np.shape(grad_gauss))
            print("pred[i]:")
            print(np.shape(pred[i]))
            print("y[i]:")
            print(np.shape(y[i]))
            grad = (pred[i] - y[i]) @ (self.weights[j]*grad_gauss)
            # można zrb macierz ixj i zapisywać każdy wynik oddzielnie, a późnij policzyć sumę
            grad_sum[j] = grad_sum[j] + grad

    return grad_sum

In [70]:
n_samples = X.shape[0]
activations = np.ones((n_samples, n_centers+1))

for i in range(n_samples):
    for j in range(n_centers):
        activations[i][j+1] = gaussian_func(X[i], centers[j], sigma[j])
        weights = np.linalg.pinv(activations) @ y
        print("weights calculated")

        grad = _GD(X, y)

weights calculated
y:
(3000, 1)


C:\Users\zgore\AppData\Local\Temp\ipykernel_26292\3157987578.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  activations[i][j+1] = gaussian_func(X[i], centers[j], sigma[j])


NameError: name 'self' is not defined

In [72]:
isinstance(df_train, pd.DataFrame)

True

In [8]:
from ELM import ELM

In [35]:
def create_model(default = 300, **kwargs):
    print(default)
    model = ELM(**kwargs)
    params = {"model_class": 1, "model_type": 2, "order_dyn": 3, "y_name": 'h'+'(k)', "features": 234,"pred_mode": False}
    dictionary = params | kwargs
    return model, dictionary

In [36]:
params = {"model_class": 1, "model_type": 2, "order_dyn": 3, "y_name": 'h'+'(k)', "features": 234,"pred_mode": False}

In [37]:
model, d = create_model(num_features=6, num_hidden_neurons=3)

300


In [38]:
d

{'model_class': 1,
 'model_type': 2,
 'order_dyn': 3,
 'y_name': 'h(k)',
 'features': 234,
 'pred_mode': False,
 'num_features': 6,
 'num_hidden_neurons': 3}

In [26]:
model.num_hidden_neurons

3

In [1]:
import numpy as np

In [6]:
n_sampl = 10

In [7]:
qa = 1630000/3600
qb = 2000000/3600
q = np.vstack((np.ones((1, n_sampl))* qa, np.ones((1, n_sampl))* qb))

In [9]:
q[0]

array([452.77777778, 452.77777778, 452.77777778, 452.77777778,
       452.77777778, 452.77777778, 452.77777778, 452.77777778,
       452.77777778, 452.77777778])

In [11]:
q[1][0]

555.5555555555555

In [13]:
x0 = [65, 66, 65, 66]
tau_u = 0
tau_y = 0

In [14]:
x = np.empty((4, n_sampl))
for i in range(len(x0)):
    x[i, 0:max(tau_u, tau_y, 1)] = x0[i]

In [17]:
F = np.array(
    [[1, 0, 0, 0],
    [0, 1, 0, 0]])

x = np.empty((4, n_sampl))
for i in range(len(x0)):
    x[i, 0:max(tau_u, tau_y, 1)] = x0[i]
y = np.empty((4, n_sampl))
z = F @ x

In [18]:
z

array([[6.50000000e+001, 1.38077037e-311, 1.69121095e-306,
        6.95174801e-310, 7.56588262e-307, 6.95174801e-310,
        1.05699242e-307, 6.95174801e-310, 2.22520831e-306,
        0.00000000e+000],
       [6.60000000e+001, 4.24399508e-311, 2.12199579e-311,
        7.56601164e-307, 0.00000000e+000, 2.47032823e-323,
        0.00000000e+000, 1.38077980e-311, 1.38078198e-311,
        8.90029543e-307]])

In [37]:
z[0][3]

6.9517480091527e-310

In [19]:
x

array([[6.50000000e+001, 1.38077037e-311, 1.69121095e-306,
        6.95174801e-310, 7.56588262e-307, 6.95174801e-310,
        1.05699242e-307, 6.95174801e-310, 2.22520831e-306,
        0.00000000e+000],
       [6.60000000e+001, 4.24399508e-311, 2.12199579e-311,
        7.56601164e-307, 0.00000000e+000, 2.47032823e-323,
        0.00000000e+000, 1.38077980e-311, 1.38078198e-311,
        8.90029543e-307],
       [6.50000000e+001, 0.00000000e+000, 8.90111708e-307,
        6.89772896e-307, 8.90104239e-307, 1.42417221e-306,
        0.00000000e+000, 7.41098469e-323, 1.60221208e-306,
        8.45602762e-307],
       [6.60000000e+001, 7.41098469e-323, 1.42417221e-306,
        0.00000000e+000, 1.37961302e-306, 1.60221208e-306,
        8.45602762e-307, 1.37961913e-306, 5.08887615e-322,
        2.56765117e-312]])

In [26]:
step_dur = 3
SP_x1 = np.array([65, 30, 90, 120, 50])
SP_x2 = np.array([65, 100, 40, 80, 50])
SP_x = np.vstack((SP_x1, SP_x2))
SP_x = np.repeat(np.round(SP_x, 2), step_dur, axis=1)

In [27]:
SP_x

array([[ 65,  65,  65,  30,  30,  30,  90,  90,  90, 120, 120, 120,  50,
         50,  50],
       [ 65,  65,  65, 100, 100, 100,  40,  40,  40,  80,  80,  80,  50,
         50,  50]])

In [33]:
F = np.array(
        [[1, 0, 0, 0],
        [0, 1, 0, 0]])
x = np.empty((4, n_sampl))
for i in range(len(x0)):
    x[i, 0:max(tau_u, tau_y, 1)] = x0[i]
y = np.empty((4, n_sampl))
z = F @ x
e = np.zeros((2, n_sampl))

In [34]:
np.shape(z)

(2, 10)

In [35]:
np.shape(SP_x)

(2, 15)